name: MagmaCore
version: '${project.version}'
main: dev.tobys.magma.Magma
api-version: 1.16
authors: [ Tobys__ ]
softdepend: [PlaceholderAPI]
commands:
  reloadconfig:
  gmc:
  gms:
permissions:
  creative.use:
    description: Allows players to switch to creative mode.
    default: op
  creative.others:
    description: Allows players to switch other players to creative mode.
    default: op○○c○